name: CI
on:
  push:
    branches:
      - '*'
jobs:
  in-docker_test:
    name: Testes Automatizados
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set JDK
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Cache de Deps
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Executar Teste
        run: mvn -B test